plugins {
    id "com.android.application"
}

android {
    namespace "com.gsgsviewer.app"
    compileSdk 34

    defaultConfig {
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildFeatures {
        buildConfig true
    }

    flavorDimensions "app"
    productFlavors {
        viewer {
            dimension "app"
            applicationId "com.gsgsviewer.app"
            resValue "string", "app_name", "gsgsViewer"
            buildConfigField "String", "START_URL", '"https://appassets.androidplatform.net/assets/index.html"'
        }
        chat {
            dimension "app"
            applicationId "com.gsgsviewer.chat"
            resValue "string", "app_name", "gsgsChat"
            buildConfigField "String", "START_URL", '"https://bleaxedware0.github.io/svgviewer/chat.html"'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "androidx.webkit:webkit:1.11.0"
}
